const validation_pre = (text: string) => `Zəhmət olmasa ${text} daxil edin`;

export const EN = {
  Nav_Menu_Home: "Ana səhifə",
  Nav_Menu_AboutUs: "Haqqımızda",
  Nav_Menu_FAQ: "FAQ",
  Nav_Menu_Contacts: "Əlaqə",
  Nav_Menu_Blog: "Bloq",
  Buttons_MoreInfo: "Daha ətraflı",
  Buttons_Services: "Xidmətlərimiz",
  Buttons_Apply: "Müraciət et",
  Buttons_Visa: "Apply for visa",
  Buttons_Confirm: "Təsdiqlə",
  Buttons_ContinueToPayment: "Continue to payment",
  Buttons_AddAnotherPerson: "Add another person",
  Buttons_RemovePerson: "Remove person",
  Buttons_Close: "Bağla",
  Buttons_GoBack: "Geri qayıt",
  Buttons_ReadBlog: "Bloqu oxu",
  NoContent_Service: "Üzr istəyirik, kriteriyaya uyğun xidmət tapılmadı",
  Error_NotFound_Title: "Tapılmadı",
  Error_NotFound_Content:
    "Üzr istəyirik, ama axtardığınız məlumatı tapmaq mümkün olmadı",
  Error_ServerError_Title: "Daxili Xəta",
  Error_ServerError_Content:
    "Üzr istəyirik, sorğunuzu yerinə yetirərkən server daxili xəta baş verdi",
  Error_NoFittingContent:
    "Unfortunately, no appropriate result was found based on your query.",
  Footer_Columns_About_Title: "Haqqımızda",
  Footer_Columns_Legal_Title: "Hüquqi",
  Footer_Columns_Legal_TermsAndConditions: "Qaydalar və şərtlər",
  Footer_Columns_Legal_PrivacyPolicy: "Məxfilik siyasəti",
  Footer_Columns_Social_Title: "Sosial",
  Footer_Copyright: "Bütün huquqlar qorunur.",
  Banners_Promotion_Text: "Vaxt itirmədən viza almağa hazırsınız?",
  Banners_Home_Text: "emal vaxtını və xərcləri nəzərdən keçirin",
  VisaCard_ProcessingDetails: "Processing details",
  VisaCard_TotalFee: "Total fee",
  VisaCard_Tip: "* Includes Processing fee",
  VisaCard_ProcessingDetails_AsFastAs: "Sürəti",
  VisaCard_ProcessingDetails_DurationOfStay: "Duration of stay",
  Blog_Popular_Blogs: "Popular blogs",
  Blog_Categories: "Bloq Kateqoriyaları",
  Blog_Posts_ViewAll: "Hamısına bax",
  Blog_Topics: "Mövzular",
  Blog_RecentPost: "Recent Post",
  Blog_RelatedPosts: "Related posts",
  Contact_Header_Title: "Get in touch!",
  Contact_Header_Subtitle: "Contact us for a quote, help it to join the team",
  Contact_Form_Title: "Still have a question?",
  Contact_Form_Fields_Name: "Name",
  Contact_Form_Fields_Email: "Email",
  Contact_Form_Fields_Phone: "Phone",
  Contact_Form_Fields_Subject: "Subject",
  Contact_Form_Fields_Comment: "Comment",
  Steps_Title: 'E-visa to "Country" in 3 easy steps!',
  Apply_Select_Nationality: "Choose your Nationality",
  AboutUs_Title: "About Us",
  AboutUs_Content:
    "Vizam.az is an online platform that provides services in obtaining travel, education and business trip visas to any country worldwide. Visa application processes are complex, time-consuming and require a detailed approach. Our company does its best to help its customers to get a visa and minimizes their involvement in the process. The user-friendly interface of our website, specialization exclusively in visa issues and wide database, containing all information about visa requirements of any country in the world make Vizam.az unique in the service market.",
  OrderSummary_Title: "Order Summary",
  OrderSummary_PromoCode: "Promo code",
  OrderSummary_DiscountCode: "Discount code",
  OrderSummary_TotalFee: "Total fee",
  OrderSummary_Processing_Title: "Processing details",
  OrderSummary_Processing_Fee: "Processing fee",
  OrderSummary_Processing_Residency: "Residency",
  OrderSummary_Processing_Destination: "Destination",
  OrderSummary_Processing_AsFastAs: "As fast as",
  OrderSummary_Processing_DurationOfStay: "Duration of stay",
  OrderSummary_GeneralInformation: "General Information",
  OrderSummary_RequiredDocuments: "Required documents",
};
